apiVersion: v1
kind: Service
metadata:
  name: $SVC_NAME
  labels:
    app: $APP_NAME
spec:
  selector:
    app: $APP_NAME
  ports:
  - protocol: $SVC_PROTOCOL
    name: http
    port: $SVC_PORT
    targetPort: $SVC_TARGET_PORT
    nodePort: $SVC_NODEPORT
  type: $SVC_TYPE